query Course($slug: String!, $id: ID) {
  courseBySlug(slug: $slug) {
    id
    title
    description
    slug
    lessons {
      id
      title
      content
      youtubeVideoId
    }
    completed_lessons(where: { user: $id }) {
      lesson {
        id
      }
      userYoutubeVideo
    }
  }
}
