query Courses($ids: [String]) {
  courses(where: { id_nin: $ids}) {
    id
    title
    description
		slug
    users {
      id
    }
    lessons {
      id
      title
      youtubeVideoId
    }
  }
}
