query Course($slug: String!) {
  courseBySlug(slug: $slug) {
    title
    description
    slug
    lessons {
      title
      completed
      content
      youtubeVideoId
      userYoutubeVideoUrl
    }
  }
}
