query UserCourses($id: ID!) {
  courses(where: { users: { id: $id } }) {
    id
    title
    description
    slug
    users {
      id
    }
    lessons {
      title
      youtubeVideoId
    }
  }
}
